import {
  SiCplusplus,
  SiCss,
  SiDrizzle,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiGit,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiOpenjdk,
  SiPostgresql,
  SiPostman,
  SiReact,
  SiSelenium,
  SiShadcnui,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiClaude,
  SiGooglegemini,
  SiOpenai,
  SiDocker,
} from "react-icons/si";
import {
  BoxesIcon,
  BugIcon,
  ClipboardCheckIcon,
  CloudIcon,
  ComponentIcon,
  CpuIcon,
  DatabaseIcon,
  DatabaseZapIcon,
  FilmIcon,
  FlaskConicalIcon,
  GaugeIcon,
  ImageIcon,
  LayersIcon,
  LayoutTemplateIcon,
  ListChecksIcon,
  ListTreeIcon,
  LockKeyholeIcon,
  NetworkIcon,
  PencilRulerIcon,
  PlugIcon,
  PuzzleIcon,
  RadioIcon,
  RefreshCwIcon,
  RouteIcon,
  SearchIcon,
  SmartphoneIcon,
  TableIcon,
  WifiIcon,
  WorkflowIcon,
} from "lucide-react";

export interface TechStackItem {
  key: string;
  title: string;
  /** Omit for concepts/skills that don't have a single canonical homepage. */
  href?: string;
  /** Brand logo if one exists; otherwise a generic icon representing the concept. */
  icon: React.ReactNode;
  categories: string[];
}

// Edit, add, or remove entries here. `categories` controls which group(s)
// an item shows up under — an item can belong to more than one.
export const TECH_STACK: TechStackItem[] = [
  // Programming Languages
  {
    categories: ["Programming Languages"],
    href: "https://www.java.com",
    icon: <SiOpenjdk />,
    key: "java",
    title: "Java",
  },
  {
    categories: ["Programming Languages"],
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    icon: <SiJavascript />,
    key: "javascript",
    title: "JavaScript",
  },
  // {
  //   categories: ["Programming Languages"],
  //   href: "https://www.typescriptlang.org",
  //   icon: <SiTypescript />,
  //   key: "typescript",
  //   title: "TypeScript",
  // },
  {
    categories: ["Programming Languages"],
    href: "https://isocpp.org",
    icon: <SiCplusplus />,
    key: "cpp",
    title: "C++",
  },
  {
    categories: ["Programming Languages"],
    icon: <TableIcon />,
    key: "sql",
    title: "SQL",
  },

  // Frontend
  {
    categories: ["Frontend"],
    href: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    icon: <SiHtml5 />,
    key: "html5",
    title: "HTML5",
  },
  {
    categories: ["Frontend"],
    href: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    icon: <SiCss />,
    key: "css3",
    title: "CSS3",
  },
  // {
  //   categories: ["Frontend"],
  //   href: "https://react.dev",
  //   icon: <SiReact />,
  //   key: "react",
  //   title: "React.js",
  // },
  {
    categories: ["Frontend"],
    href: "https://nextjs.org",
    icon: <SiNextdotjs />,
    key: "nextjs",
    title: "Next.js",
  },
  {
    categories: ["Frontend"],
    href: "https://tailwindcss.com",
    icon: <SiTailwindcss />,
    key: "tailwindcss",
    title: "Tailwind CSS",
  },
  {
    categories: ["Frontend"],
    href: "https://ui.shadcn.com",
    icon: <SiShadcnui />,
    key: "shadcn-ui",
    title: "ShadCN UI",
  },
  {
    categories: ["Frontend"],
    icon: <SmartphoneIcon />,
    key: "responsive-web-development",
    title: "Responsive Web Development",
  },

  // Backend
  // {
  //   categories: ["Backend"],
  //   href: "https://nodejs.org",
  //   icon: <SiNodedotjs />,
  //   key: "nodejs",
  //   title: "Node.js",
  // },
  // {
  //   categories: ["Backend"],
  //   href: "https://expressjs.com",
  //   icon: <SiExpress />,
  //   key: "express",
  //   title: "Express.js",
  // },
  // {
  //   categories: ["Backend"],
  //   href: "https://fastapi.tiangolo.com",
  //   icon: <SiFastapi />,
  //   key: "fastapi",
  //   title: "FastAPI",
  // },
  // {
  //   categories: ["Backend"],
  //   icon: <NetworkIcon />,
  //   key: "rest-api-development",
  //   title: "RESTful API Development",
  // },
  // {
  //   categories: ["Backend"],
  //   icon: <LockKeyholeIcon />,
  //   key: "auth",
  //   title: "Authentication & Authorization",
  // },
//workflow and Ai 
{
  categories: ["Workflow & AI"],
  href: "https://claude.ai",
  icon: <SiClaude />,
  key: "claude",
  title: "Claude",
},
{
  categories: ["Workflow & AI"],
  href: "https://gemini.google.com",
  icon: <SiGooglegemini />,
  key: "gemini",
  title: "Gemini",
},
{
  categories: ["Workflow & AI"],
  href: "https://chatgpt.com",
  icon: <SiOpenai />,
  key: "chatgpt",
  title: "ChatGPT",
},
{
  categories: ["Workflow & AI"],
  href: "https://git-scm.com",
  icon: <SiGit />,
  key: "git",
  title: "Git",
},
{
  categories: ["Workflow & AI"],
  href: "https://github.com",
  icon: <SiGithub />,
  key: "github",
  title: "GitHub",
},
{
  categories: ["Workflow & AI"],
  href: "https://www.docker.com",
  icon: <SiDocker />,
  key: "docker",
  title: "Docker",
},
{
  categories: ["Workflow & AI"],
  href: "https://vercel.com",
  icon: <SiVercel />,
  key: "vercel",
  title: "Vercel",
},
  // Databases
  // {
  //   categories: ["Databases"],
  //   href: "https://www.postgresql.org",
  //   icon: <SiPostgresql />,
  //   key: "postgresql",
  //   title: "PostgreSQL",
  // },
  // {
  //   categories: ["Databases"],
  //   href: "https://www.mysql.com",
  //   icon: <SiMysql />,
  //   key: "mysql",
  //   title: "MySQL",
  // },
  // {
  //   categories: ["Databases"],
  //   href: "https://www.mongodb.com",
  //   icon: <SiMongodb />,
  //   key: "mongodb",
  //   title: "MongoDB",
  // },
  // {
  //   categories: ["Databases"],
  //   href: "https://neon.tech",
  //   icon: <DatabaseZapIcon />,
  //   key: "neon-db",
  //   title: "Neon DB",
  // },
  // {
  //   categories: ["Databases"],
  //   href: "https://orm.drizzle.team",
  //   icon: <SiDrizzle />,
  //   key: "drizzle-orm",
  //   title: "Drizzle ORM",
  // },

  // DevOps & Cloud
  // {
  //   categories: ["DevOps & Cloud"],
  //   href: "https://git-scm.com",
  //   icon: <SiGit />,
  //   key: "git",
  //   title: "Git",
  // },
  // {
  //   categories: ["DevOps & Cloud"],
  //   href: "https://github.com",
  //   icon: <SiGithub />,
  //   key: "github",
  //   title: "GitHub",
  // },
  // {
  //   categories: ["DevOps & Cloud"],
  //   icon: <WorkflowIcon />,
  //   key: "ci-cd",
  //   title: "CI/CD Pipelines",
  // },
  // {
  //   categories: ["DevOps & Cloud"],
  //   href: "https://aws.amazon.com",
  //   icon: <CloudIcon />,
  //   key: "aws",
  //   title: "AWS (Basics)",
  // },
  // {
  //   categories: ["DevOps & Cloud"],
  //   href: "https://vercel.com",
  //   icon: <SiVercel />,
  //   key: "vercel",
  //   title: "Vercel",
  // },

  // Testing & QA
  {
    categories: ["Testing & QA"],
    icon: <ClipboardCheckIcon />,
    key: "manual-testing",
    title: "Manual Testing",
  },
  {
    categories: ["Testing & QA"],
    icon: <ListChecksIcon />,
    key: "test-case-design",
    title: "Test Case Design",
  },
  {
    categories: ["Testing & QA"],
    icon: <FlaskConicalIcon />,
    key: "unit-testing",
    title: "Unit Testing",
  },
  {
    categories: ["Testing & QA"],
    icon: <RouteIcon />,
    key: "e2e-testing",
    title: "End-to-End Testing",
  },
  {
    categories: ["Testing & QA"],
    href: "https://www.postman.com",
    icon: <SiPostman />,
    key: "postman",
    title: "Postman API Testing",
  },
  // {
  //   categories: ["Testing & QA"],
  //   href: "https://www.selenium.dev",
  //   icon: <SiSelenium />,
  //   key: "selenium",
  //   title: "Selenium (Basic)",
  // },
  {
    categories: ["Testing & QA"],
    icon: <BugIcon />,
    key: "bug-reporting",
    title: "Bug Reporting",
  },

  // UI/UX & Design
  {
    categories: ["UI/UX & Design"],
    href: "https://www.figma.com",
    icon: <SiFigma />,
    key: "figma",
    title: "Figma",
  },
  {
    categories: ["UI/UX & Design"],
    href: "https://www.adobe.com/products/photoshop.html",
    icon: <ImageIcon />,
    key: "photoshop",
    title: "Adobe Photoshop",
  },
  {
    categories: ["UI/UX & Design"],
    href: "https://www.adobe.com/products/illustrator.html",
    icon: <PencilRulerIcon />,
    key: "illustrator",
    title: "Adobe Illustrator",
  },
  {
    categories: ["UI/UX & Design"],
    href: "https://www.adobe.com/products/aftereffects.html",
    icon: <FilmIcon />,
    key: "after-effects",
    title: "Adobe After Effects",
  },
  {
    categories: ["UI/UX & Design"],
    icon: <LayoutTemplateIcon />,
    key: "wireframing",
    title: "Wireframing",
  },
  {
    categories: ["UI/UX & Design"],
    icon: <LayersIcon />,
    key: "prototyping",
    title: "Prototyping",
  },
  // {
  //   categories: ["UI/UX & Design"],
  //   icon: <ComponentIcon />,
  //   key: "design-systems",
  //   title: "Design Systems",
  // },
  // {
  //   categories: ["UI/UX & Design"],
  //   icon: <SmartphoneIcon />,
  //   key: "responsive-design",
  //   title: "Responsive Design",
  // },

  // Computer Science Fundamentals
  {
    categories: ["Computer Science Fundamentals"],
    icon: <ListTreeIcon />,
    key: "dsa",
    title: "Data Structures & Algorithms",
  },
  {
    categories: ["Computer Science Fundamentals"],
    icon: <BoxesIcon />,
    key: "oop",
    title: "OOP",
  },
  {
    categories: ["Computer Science Fundamentals"],
    icon: <DatabaseIcon />,
    key: "dbms",
    title: "DBMS",
  },
  {
    categories: ["Computer Science Fundamentals"],
    icon: <CpuIcon />,
    key: "operating-systems",
    title: "Operating Systems",
  },
  {
    categories: ["Computer Science Fundamentals"],
    icon: <WifiIcon />,
    key: "computer-networks",
    title: "Computer Networks",
  },
  {
    categories: ["Computer Science Fundamentals"],
    icon: <WorkflowIcon />,
    key: "sdlc",
    title: "SDLC",
  },
  {
    categories: ["Computer Science Fundamentals"],
    icon: <RefreshCwIcon />,
    key: "agile",
    title: "Agile",
  },
  // {
  //   categories: ["Computer Science Fundamentals"],
  //   icon: <ComponentIcon />,
  //   key: "mvc",
  //   title: "MVC Architecture",
  // },

  // Additional Skills
  // {
  //   categories: ["Additional Skills"],
  //   icon: <GaugeIcon />,
  //   key: "performance-optimization",
  //   title: "Performance Optimization",
  // },
  // {
  //   categories: ["Additional Skills"],
  //   icon: <PlugIcon />,
  //   key: "api-integration",
  //   title: "API Integration",
  // },
  // {
  //   categories: ["Additional Skills"],
  //   icon: <BugIcon />,
  //   key: "debugging",
  //   title: "Debugging",
  // },
  // {
  //   categories: ["Additional Skills"],
  //   icon: <RadioIcon />,
  //   key: "real-time-apps",
  //   title: "Real-Time Application Development",
  // },
  // {
  //   categories: ["Additional Skills"],
  //   icon: <SearchIcon />,
  //   key: "seo-fundamentals",
  //   title: "SEO Fundamentals",
  // },
  // {
  //   categories: ["Additional Skills"],
  //   icon: <PuzzleIcon />,
  //   key: "problem-solving",
  //   title: "Problem Solving",
  // },
];
